@dataclass
class SofarModbusSensorEntityDescription(BaseModbusSensorEntityDescription):
    """A class that describes Sofar Modbus sensor entities."""
    order16: int = Endian.Big
    order32: int = Endian.Big
    unit: int = REGISTER_U16
    register_type: int= REG_HOLDING

SENSOR_TYPES: list[SofarModbusSensorEntityDescription] = [ 

###
#
# On Grid Output
#
###

    SofarModbusSensorEntityDescription(
        name = "Serial Number",
        key = "serial_number",
        native_unit_of_measurement = ELECTRIC_CURRENT_AMPERE,
        device_class = DEVICE_CLASS_CURRENT,
        register = 0x445,
        unit=REGISTER_STR,
        wordcount=7,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Grid Frequency",
        key = "grid_frequency",
        native_unit_of_measurement = FREQUENCY_HERTZ,
        device_class = DEVICE_CLASS_FREQUENCY,
        register = 0x484,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output Total",
        key = "activepower_output_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x485,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower Output Total",
        key = "reactivepower_output_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x486,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ApparentPower Output Total",
        key = "apparentpower_output_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x487,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC Total",
        key = "activepower_pcc_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x488,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower PCC Total",
        key = "reactivepower_pcc_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x489,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ApparentPower PCC Total",
        key = "apparentpower_pcc_total",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x48A,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage R",
        key = "voltage_r",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x48D,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current Output R",
        key="current_output_r",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x48E,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output R",
        key = "activepower_output_r",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x48F,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower Output R",
        key = "reactivepower_output_r",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x490,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor Output R",
        key = "powerfactor_output_r",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x491,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current PCC R",
        key="current_pcc_r",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x492,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC R",
        key = "activepower_pcc_r",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x493,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower PCC R",
        key = "reactivepower_pcc_r",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x494,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor PCC R",
        key = "powerfactor_pcc_r",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x495,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage S",
        key = "voltage_s",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x498,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current Output S",
        key="current_output_s",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x499,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output S",
        key = "activepower_output_s",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x49A,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower Output S",
        key = "reactivepower_output_S",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x49B,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor Output S",
        key = "powerfactor_output_s",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x49C,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current PCC S",
        key="current_pcc_s",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x49D,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC S",
        key = "activepower_pcc_s",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x49E,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower PCC S",
        key = "reactivepower_pcc_s",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x49F,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor PCC S",
        key = "powerfactor_pcc_s",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x4A0,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage T",
        key = "voltage_t",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4A3,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current Output T",
        key="current_output_t",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4A4,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output T",
        key = "activepower_output_t",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4A5,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower Output T",
        key = "reactivepower_output_t",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4A6,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor Output T",
        key = "powerfactor_output_t",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x4A7,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current PCC T",
        key="current_pcc_t",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4A8,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC T",
        key = "activepower_pcc_t",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4A9,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ReactivePower PCC T",
        key = "reactivepower_pcc_t",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4AA,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "PowerFactor PCC T",
        key = "powerfactor_pcc_t",
        device_class = DEVICE_CLASS_POWER_FACTOR,
        register = 0x4AB,
        unit = REGISTER_S16,
        scale = 0.001,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PV Ext",
        key = "activepower_pv_ext",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4AE,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Load Sys",
        key = "activepower_load_sys",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4AF,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage Phase L1N",
        key = "voltage_phase_l1n",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4B0,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current Output L1N",
        key="current_output_l1n",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4B1,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output L1N",
        key = "activepower_output_l1n",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4B2,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current PCC L1N",
        key="current_pcc_l1n",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4B3,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC L1N",
        key = "activepower_pcc_l1n",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4B4,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage Phase L2N",
        key = "voltage_phase_l2n",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4B5,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current Output L2N",
        key="current_output_l2n",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4B6,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower Output L2N",
        key = "activepower_output_l2n",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4B7,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name="Current PCC L2N",
        key="current_pcc_l2n",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=DEVICE_CLASS_CURRENT,
        register = 0x4B8,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "ActivePower PCC L2N",
        key = "activepower_pcc_l2n",
        native_unit_of_measurement = ENERGY_KILO_WATT_HOUR,
        device_class = DEVICE_CLASS_ENERGY,
        register = 0x4B8,
        unit = REGISTER_S16,
        scale = 0.01,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage Line L1",
        key = "voltage_line_l1",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4BA,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage Line L2",
        key = "voltage_line_l2",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4BB,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),
    SofarModbusSensorEntityDescription(
        name = "Voltage Line L3",
        key = "voltage_line_l3",
        native_unit_of_measurement = ELECTRIC_POTENTIAL_VOLT,
        device_class = DEVICE_CLASS_VOLTAGE,
        register = 0x4BC,
        scale = 0.1,
        allowedtypes = HYBRID | X3,
    ),

###
#
# Off Grid Output (0x0500-0x057F)
#
###

###
#
# PV Input (0x0580-0x05FF)
#
###

###
#
# Battery Input (0x0600-0x067F)
#
###

###
#
# Electric Power (0x0680-0x06BF)
#
###

###
#
# Basic Parameter Configuration (0x1000-0x10FF)
#
###

###
#
# Remote Control (0x1100-0x12FF)
#
###

]